{
 "title": "DDS Hosts",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU % Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rti_routing_service_cpu{exported_instance=\"/routing_services/AggregationRouting\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_routing_service_cpu{exported_instance=\"/routing_services/DDStoKafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "rti_routing_service_mem_free{exported_instance=\"/routing_services/AggregationRouting\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_routing_service_mem_free{exported_instance=\"/routing_services/DDStoKafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rti_routing_service_uptime{exported_instance=\"/routing_services/AggregationRouting\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_routing_service_uptime{exported_instance=\"/routing_services/DDStoKafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "rti_routing_service_swap_free{exported_instance=\"/routing_services/AggregationRouting\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_routing_service_swap_free{exported_instance=\"/routing_services/DDStoKafka\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}