{
 "title": "DDS Routing to Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain Route Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rti_domain_route_latency{domain_route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    }
   ]
  },
  {
   "title": "Topic Route Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rti_route_latency{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_vehicle\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_route_latency{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_aggregated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Domain Routes Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Input Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rti_domain_route_input_samples{domain_route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    }
   ]
  },
  {
   "title": "Output Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rti_domain_route_output_samples{domain_route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    }
   ]
  },
  {
   "title": "Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rti_domain_route_input_bytes{domain_route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    }
   ]
  },
  {
   "title": "Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rti_domain_route_output_bytes{domain_route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    }
   ]
  },
  { "title": "Topic Routes Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Input Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rti_route_input_samples{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_vehicle\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_route_input_samples{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_aggregated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rti_route_output_samples{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_vehicle\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_route_output_samples{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_aggregated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rti_route_input_bytes{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_vehicle\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_route_input_bytes{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_aggregated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rti_route_output_bytes{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_vehicle\"}",
     "legendFormat": "{{Domain 1 to 10}}"
    },
    {
     "expr": "rti_route_output_bytes{route=\"/routing_services/DDStoKafka/domain_routes/dds_to_kafka_route/sessions/bridge_session/routes/dds_to_kafka_aggregated\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}